title: Ben Polinsky | GIS Portfolio
description: Maps and spatial analysis from GIS Fundamentals coursework
remote_theme: pages-themes/Minimal

# Enable GitHub Pages plugin
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  

# Set navigation order
nav_order: 1

# Add your navigation structure (optional override)
nav:
  - title: "Home"
    url: /
  - title: "Maps"
    url: /maps
  - title: "About"
    url: /about
  - title: "Contact"
    url: /contact

# Optional extras
color_scheme: light
logo: /assets/logo.jpeg
search_enabled: true
