title: Ben Polinsky Home
description: Portfolio and projects of Ben Polinsky
remote_theme: pages-themes/Minimal

# Enable GitHub Pages plugin
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  

# Set navigation order
nav_order: 1

# Add your navigation structure (optional override)
nav:
  - title: "Home"
    url: /
  - title: "About Me"
    url: /about
  - title: "Projects"
    url: /projects
  - title: "Maps"
    url: /maps
  - title: "Contact"
    url: /contact

# Optional extras
color_scheme: light
logo: /assets/logo.jpeg
search_enabled: true
